### ISSUE TITLE
Trouble placing blocks and opening GUI's

### ISSUE THREAD

**Issue by lightningwolfblade** [LukeGrahamLandry/tribes-mod#1]
So basically whenever I'm in the wilderness hemisphere everything fine, but as soon i go to any other hemisphere i can't place blocks, can't break blocks and can't access any type of GUI's only commands and my inventory

**Comment by LukeGrahamLandry** [comment]
That’s intended behaviour. You must  choose a hemisphere for your tribe to access (by default you can only do this once you have a tier two tribe). If you disapprove, this feature can be disabled in the config.  More info on the wiki: https://github.com/LukeGrahamLandry/tribes-mod/blob/main/wiki.md#tribe-hemisphere-

**Comment by lightningwolfblade** [comment]
Thank you very much, sorry for wasting your time.
