### ISSUE TITLE
Feature Request: Configurable Hud Display

### ISSUE THREAD

**Issue by ClockwerkKaiser** [LukeGrahamLandry/tribes-mod#2]
After looking through the configs, I've realized that there is no option to move the location of the "Area Display" at the top left of the HUD. 

This is a humble request to have an option to be able to move it, either freely, or in preset locations (TOP-LEFT, TOP-RIGHT, TOP-CENTER, BOTTOM-LEFT, BOTTOM-RIGHT, etc).

Not only would it be great to have that additional customization, but it would also avoid conflicts with others mods which add information to the HUD.

**Comment by LukeGrahamLandry** [comment]
good idea, I'll try to add it in the next version

**Comment by LukeGrahamLandry** [comment]
added in 1.73
open the client to generate the default config file then edit minecraft/config/tribes-client.toml to select your preferred position (the default file has the options listed in a comment)
